'use client'
import { Activity, BarChart3 } from 'lucide-react'
import { Bar, BarChart, CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { Card, CardContent } from '@/components/ui/card'
import { ankylosisData, hypertensionData } from '@/lib/site-data'

export default function CaseStudies() { return <section id="case-studies" className="bg-white py-24"><div className="mx-auto max-w-7xl px-5 lg:px-8"><p className="text-sm font-semibold uppercase tracking-[.18em] text-teal-700">Études de cas</p><h2 className="mt-4 max-w-2xl text-4xl font-bold tracking-tight text-slate-950 sm:text-5xl">Des résultats qui racontent une histoire.</h2><Tabs defaultValue="ankylosis" className="mt-12"><TabsList className="h-auto w-full justify-start gap-2 overflow-x-auto rounded-none border-b border-slate-200 bg-transparent p-0"><TabsTrigger value="ankylosis" className="shrink-0 rounded-t-lg rounded-b-none px-4 py-3 data-[state=active]:bg-slate-900 data-[state=active]:text-white">Ankylose temporo-mandibulaire</TabsTrigger><TabsTrigger value="hypertension" className="shrink-0 rounded-t-lg rounded-b-none px-4 py-3 data-[state=active]:bg-slate-900 data-[state=active]:text-white">Hypertension artérielle</TabsTrigger></TabsList><TabsContent value="ankylosis"><CaseCard icon={<BarChart3 />} title="Séquelles post-chirurgicales de l’ankylose temporo-mandibulaire" meta="N=25 · Étude transversale" text="L’observance de la kinésithérapie apparaît comme un facteur clé dans la prévention de la ré-ankylose. La visualisation met en contraste les deux profils d’observance." chart={<ResponsiveContainer width="100%" height={300}><BarChart data={ankylosisData} margin={{ top: 15, right: 15, bottom: 10, left: 0 }}><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#e2e8f0" /><XAxis dataKey="name" tick={{ fontSize: 11 }} /><YAxis unit="%" /><Tooltip /><Bar dataKey="succes" name="Succès" fill="#0d9488" radius={[5,5,0,0]} /><Bar dataKey="reankylose" name="Ré-ankylose" fill="#334155" radius={[5,5,0,0]} /></BarChart></ResponsiveContainer>} /></TabsContent><TabsContent value="hypertension"><CaseCard icon={<Activity />} title="Facteurs associés à l’hypertension artérielle" meta="Analyse exploratoire · Pression systolique" text="Une première lecture met en évidence une tendance ascendante entre l’âge et la pression artérielle systolique, à approfondir par une modélisation multivariée." chart={<ResponsiveContainer width="100%" height={300}><LineChart data={hypertensionData} margin={{ top: 15, right: 15, bottom: 10, left: 0 }}><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#e2e8f0" /><XAxis dataKey="age" unit=" ans" /><YAxis unit=" mmHg" /><Tooltip /><Line type="monotone" dataKey="pression" name="Pression systolique" stroke="#0d9488" strokeWidth={3} dot={{ fill: '#0d9488', r: 5 }} /></LineChart></ResponsiveContainer>} /></TabsContent></Tabs></div></section> }
function CaseCard({ icon, title, meta, text, chart }: { icon: React.ReactNode; title: string; meta: string; text: string; chart: React.ReactNode }) { return <Card className="mt-8 overflow-hidden border-slate-200"><CardContent className="grid gap-10 p-6 lg:grid-cols-[.8fr_1.2fr] lg:p-10"><div><div className="grid size-11 place-items-center rounded-xl bg-teal-50 text-teal-700">{icon}</div><h3 className="mt-6 text-2xl font-bold tracking-tight text-slate-950">{title}</h3><p className="mt-3 text-sm font-semibold text-teal-700">{meta}</p><p className="mt-5 leading-7 text-slate-600">{text}</p></div><div className="min-w-0 self-center">{chart}</div></CardContent></Card> }
