'use client'
import { useState } from 'react'
import Image from 'next/image'
import { Check, DatabaseZap, X } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Card, CardContent } from '@/components/ui/card'
import { cleanRows, rawRows } from '@/lib/site-data'
const headers = ['ID', 'Âge', 'Sexe', 'Date', 'Tabac']
export default function DataCleaningShowcase() { const [cleaned, setCleaned] = useState(false); const rows = cleaned ? cleanRows : rawRows; return <section className="bg-slate-50 py-24"><div className="mx-auto max-w-7xl px-5 lg:px-8"><div className="grid gap-10 lg:grid-cols-[.75fr_1.25fr] lg:items-center"><div><Image src="/images/data-cleaning-accent.png" alt="" role="presentation" width={480} height={204} className="mb-6 h-auto w-full max-w-sm" /><p className="text-sm font-semibold uppercase tracking-[.18em] text-teal-700">La méthode</p><h2 className="mt-4 text-4xl font-bold tracking-tight text-slate-950">Une donnée propre est déjà une première analyse.</h2><p className="mt-5 leading-7 text-slate-600">Avant tout test statistique, je rends la base cohérente, traçable et prête à répondre à votre question de recherche.</p><div className="mt-7 inline-flex rounded-xl border border-slate-200 bg-white p-1"><Button variant={!cleaned ? 'default' : 'ghost'} onClick={() => setCleaned(false)} className={!cleaned ? 'bg-slate-900' : ''}>Base brute</Button><Button variant={cleaned ? 'default' : 'ghost'} onClick={() => setCleaned(true)} className={cleaned ? 'bg-teal-600 text-white hover:bg-teal-700' : ''}>Base nettoyée</Button></div></div><Card className="overflow-hidden border-slate-200"><CardContent className="p-0"><div className="flex items-center gap-3 border-b border-slate-200 px-5 py-4"><DatabaseZap className="text-teal-600" /><span className="text-sm font-semibold text-slate-800">extrait_patients.csv</span><span className="ml-auto text-xs text-slate-500">{cleaned ? 'Standardisée' : 'À contrôler'}</span></div><div className="overflow-x-auto"><table className="w-full min-w-[560px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr>{headers.map(h => <th key={h} className="px-5 py-4 font-medium">{h}</th>)}</tr></thead><tbody>{rows.map((row, i) => <tr key={i} className="border-t border-slate-100">{row.map((cell, j) => <td key={j} className={`px-5 py-4 font-mono ${cleaned ? 'bg-teal-50/60 text-teal-800' : 'bg-rose-50/70 text-rose-700'}`}>{cell || <span className="text-rose-500">—</span>}</td>)}</tr>)}</tbody></table></div><div className={`flex items-center gap-2 border-t px-5 py-4 text-sm ${cleaned ? 'border-teal-100 bg-teal-50 text-teal-800' : 'border-rose-100 bg-rose-50 text-rose-800'}`}>{cleaned ? <Check /> : <X />}{cleaned ? 'Valeurs harmonisées et dates standardisées.' : '3 anomalies détectées dans cet extrait.'}</div></CardContent></Card></div></div></section> }
